insert into award_user (first_name, last_name, email, act_id, password, state) values ('Nicholas', 'Ford', 'nford0@businesswire.com', 1, 'aMZUyvWlaUj', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Robin', 'Burns', 'rburns1@mtv.com', 1, 'HPsPTjNfxM', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('John', 'Hart', 'jhart2@census.gov', 1, 'j6BpKs', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Samuel', 'Hunter', 'shunter3@twitpic.com', 1, 'GZSZK1406', 'Missouri');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Irene', 'Mcdonald', 'imcdonald4@123-reg.co.uk', 1, '9Xyn5mpV', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Dennis', 'Wright', 'dwright5@edublogs.org', 1, 'lENrrtO9hsxG', 'Hawaii');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Phillip', 'Garrett', 'pgarrett6@disqus.com', 1, 'gEysJlo', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kelly', 'Vasquez', 'kvasquez7@pinterest.com', 1, 'GevDDiAFAV', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Philip', 'Perry', 'pperry8@slideshare.net', 1, 'wd67qu', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jeffrey', 'Stephens', 'jstephens9@oaic.gov.au', 1, 'szk133lYDVDW', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Nancy', 'Roberts', 'nrobertsa@independent.co.uk', 1, 'XcyFyks7uq', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Peter', 'Stewart', 'pstewartb@usda.gov', 1, 'x6Okrair4q6', 'West Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Richard', 'Wells', 'rwellsc@umich.edu', 1, 'GQSjcFP', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Roger', 'Henry', 'rhenryd@nydailynews.com', 1, '9EQ7l3xhygyd', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Patricia', 'Campbell', 'pcampbelle@foxnews.com', 1, 'XDtW7zBaOS3', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Richard', 'Butler', 'rbutlerf@yahoo.com', 1, 'h2a7mlEI', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Richard', 'Howell', 'rhowellg@patch.com', 1, 'y4njAyQjs6', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gary', 'Thompson', 'gthompsonh@dailymail.co.uk', 1, 'P4CmnTZdv3i', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Susan', 'Brown', 'sbrowni@g.co', 1, 'SQDJA775', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Bruce', 'Riley', 'brileyj@fda.gov', 1, '1iw9kM9', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Mary', 'Chavez', 'mchavezk@bing.com', 1, 'qZsjp8D', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jerry', 'Morgan', 'jmorganl@sbwire.com', 1, 'RCpW06aSgHTM', 'North Dakota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('George', 'Freeman', 'gfreemanm@vk.com', 1, '7aAZ7puI', 'Mississippi');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('James', 'Powell', 'jpowelln@ycombinator.com', 1, 'wIWmP5Iy', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Scott', 'Bailey', 'sbaileyo@ft.com', 1, 'DcOYkGgbNsF', 'Massachusetts');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ryan', 'Mitchell', 'rmitchellp@paginegialle.it', 1, '0lNnVJQa', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Benjamin', 'Black', 'bblackq@goo.gl', 1, 'gJlRBmaNhG', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Thomas', 'Martinez', 'tmartinezr@blogger.com', 1, 'Y2173R4', 'Massachusetts');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jane', 'Martin', 'jmartins@gmpg.org', 1, 'JMI0KJyU', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jack', 'Palmer', 'jpalmert@deliciousdays.com', 1, 'mZdeZw1', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Brandon', 'Frazier', 'bfrazieru@paypal.com', 1, 'Eb20MAa7', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Anna', 'Hansen', 'ahansenv@tamu.edu', 1, 'K9eYXFVodHa', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carl', 'Jacobs', 'cjacobsw@tinypic.com', 1, 'W6t5GuMrh2', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Doris', 'Roberts', 'drobertsx@about.me', 1, 'F8aNrhb', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Frank', 'Moore', 'fmoorey@comsenz.com', 1, 'BhRBcx', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Harold', 'Castillo', 'hcastilloz@google.de', 1, 'N1zGxBX', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Deborah', 'Black', 'dblack10@cafepress.com', 1, 'FhRHVlP', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Lawrence', 'Campbell', 'lcampbell11@state.gov', 1, 'EMef09SGT', 'Tennessee');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Patricia', 'Fox', 'pfox12@plala.or.jp', 1, 'WXQQFKUAy54M', 'Oregon');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Marie', 'Daniels', 'mdaniels13@wikimedia.org', 1, 'smMOuvl', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Roger', 'Hudson', 'rhudson14@nyu.edu', 1, 'Dja075qrW9', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sandra', 'Payne', 'spayne15@trellian.com', 1, 'pH0rwkupgGi', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jeffrey', 'Lopez', 'jlopez16@huffingtonpost.com', 1, 'Pry65w7Qv06', 'South Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Amy', 'Castillo', 'acastillo17@ask.com', 1, 'Kw6traVejfJn', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Clarence', 'Daniels', 'cdaniels18@cnn.com', 1, 'DFfdKBFUjHG', 'North Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Paula', 'Morris', 'pmorris19@who.int', 1, 'aXRdCP', 'North Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Edward', 'Woods', 'ewoods1a@unesco.org', 1, 'BVGaXaJYgv', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Aaron', 'Ward', 'award1b@nationalgeographic.com', 1, 'jY7HqjPB', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Timothy', 'Berry', 'tberry1c@berkeley.edu', 1, 'cBMBSx', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Randy', 'Wright', 'rwright1d@buzzfeed.com', 1, 'hZ4VokhRtt', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kathy', 'Day', 'kday1e@people.com.cn', 1, 'MJHT9P', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Brian', 'Cruz', 'bcruz1f@creativecommons.org', 1, 'NOZtY7BJAfPq', 'West Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Janice', 'Edwards', 'jedwards1g@wikispaces.com', 1, 'VnkyuiFC', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Michael', 'Henderson', 'mhenderson1h@sfgate.com', 1, 'wPYMb6nfE', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ryan', 'Gutierrez', 'rgutierrez1i@seattletimes.com', 1, 'x4wA18aSlF', 'New Mexico');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Donald', 'Mcdonald', 'dmcdonald1j@paypal.com', 1, 'SImdQC4ab', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gary', 'Ferguson', 'gferguson1k@so-net.ne.jp', 1, 'meRTYtyPmE', 'Michigan');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Wayne', 'Richardson', 'wrichardson1l@illinois.edu', 1, 'WUsyfcK', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diana', 'Cruz', 'dcruz1m@xinhuanet.com', 1, '6g0B5z2', 'Massachusetts');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Andrea', 'Gray', 'agray1n@pbs.org', 1, 'H8cgKX', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('George', 'Wilson', 'gwilson1o@1688.com', 1, 'DNmwdhcvI', 'Arkansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jose', 'Vasquez', 'jvasquez1p@sakura.ne.jp', 1, 'XDO8E4cZPq', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Samuel', 'Stephens', 'sstephens1q@springer.com', 1, 'JcrFpKtcd', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Steven', 'Campbell', 'scampbell1r@github.io', 1, 'n3Tcah4l2SGj', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Daniel', 'Austin', 'daustin1s@bloglovin.com', 1, 'mRfuUUWiwNX', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gloria', 'Lawrence', 'glawrence1t@adobe.com', 1, '41zpQSlx', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joshua', 'Elliott', 'jelliott1u@ning.com', 1, 'igjz31gZzyj', 'Connecticut');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Antonio', 'Hernandez', 'ahernandez1v@posterous.com', 1, 'Vc5Nnq', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Frank', 'Baker', 'fbaker1w@weebly.com', 1, 'JGFztPOh', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Alan', 'Grant', 'agrant1x@homestead.com', 1, '190Lx2S1IQ3', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jimmy', 'Jacobs', 'jjacobs1y@ed.gov', 1, 'DSLH0A6GC', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ruby', 'Porter', 'rporter1z@oracle.com', 1, 'PHqAPRVmEXDa', 'Arkansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Eric', 'Nguyen', 'enguyen20@skyrock.com', 1, 'I6xtNAAKBf', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carolyn', 'Cox', 'ccox21@edublogs.org', 1, 'vTVBcc0L', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diane', 'Medina', 'dmedina22@hatena.ne.jp', 1, 'TcJXri', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sean', 'Miller', 'smiller23@privacy.gov.au', 1, 'r48IeRhNtBtP', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Virginia', 'Rogers', 'vrogers24@dailymotion.com', 1, 'ka9TJH', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Betty', 'Dixon', 'bdixon25@multiply.com', 1, '7w9J95Z1Yx', 'Missouri');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Janet', 'Gardner', 'jgardner26@go.com', 1, 'OOjrRP4tRW', 'Massachusetts');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Keith', 'Gardner', 'kgardner27@a8.net', 1, 'X8zoQ7rgeF', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ralph', 'Roberts', 'rroberts28@clickbank.net', 1, 'hD45OorqgO', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Fred', 'Hill', 'fhill29@youtu.be', 1, 'A2yiPYzr5d', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Shawn', 'White', 'swhite2a@jimdo.com', 1, '7qKPpwG', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jesse', 'Robertson', 'jrobertson2b@hc360.com', 1, 'djMsF8mr', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Pamela', 'Watkins', 'pwatkins2c@senate.gov', 1, '9fk78uRjja', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Roger', 'Ford', 'rford2d@guardian.co.uk', 1, 'ZBO8gHkMTiW', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jack', 'Shaw', 'jshaw2e@mail.ru', 1, 'pQheZs8LzzQ', 'Kentucky');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Patricia', 'Berry', 'pberry2f@symantec.com', 1, 'zzmzCF9XOiKE', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Nancy', 'Mcdonald', 'nmcdonald2g@yolasite.com', 1, '44lou2NNbl0', 'Kansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Samuel', 'Nelson', 'snelson2h@usa.gov', 1, 'YbY3TL5gfIU', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Nicole', 'Jacobs', 'njacobs2i@unc.edu', 1, 'AgLZZdsc', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Doris', 'Meyer', 'dmeyer2j@google.pl', 1, 'ibfoHk6O', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ann', 'Garza', 'agarza2k@cbslocal.com', 1, 'TQ5h5rceE0', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Aaron', 'Sanchez', 'asanchez2l@google.fr', 1, '0j6ankOqZKo', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Linda', 'Ramirez', 'lramirez2m@vinaora.com', 1, 'bPFOad95', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('David', 'Hill', 'dhill2n@tmall.com', 1, 's7qWNn2bZ', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Theresa', 'Rogers', 'trogers2o@washingtonpost.com', 1, 'dD20n9zdIxvR', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Shawn', 'Mason', 'smason2p@nsw.gov.au', 1, 'qfnuVK4', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Marie', 'Perkins', 'mperkins2q@vkontakte.ru', 1, 'Vr7h1LYnl', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kathy', 'Edwards', 'kedwards2r@histats.com', 1, 'J8ondn', 'Hawaii');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Andrea', 'Ward', 'award2s@google.ca', 1, 'QMswP5XVC', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Shawn', 'Morgan', 'smorgan2t@simplemachines.org', 1, 'Q8v1iJ0', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ruth', 'Turner', 'rturner2u@ustream.tv', 1, '2L8eWtiLJn', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Juan', 'Hart', 'jhart2v@goo.ne.jp', 1, 'zAKgIRu', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Laura', 'Frazier', 'lfrazier2w@sbwire.com', 1, 'Et9fRgk3o4', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Michael', 'Roberts', 'mroberts2x@scribd.com', 1, 'fThj0BqKP3', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jennifer', 'Martin', 'jmartin2y@craigslist.org', 1, 'ElhFroE6PEGW', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diane', 'Daniels', 'ddaniels2z@cnet.com', 1, 'cdsNkh', 'Maryland');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Richard', 'Moreno', 'rmoreno30@1und1.de', 1, '7xb4WWENG', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Timothy', 'Ellis', 'tellis31@mediafire.com', 1, 'uHvyIBavj', 'North Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sarah', 'Ryan', 'sryan32@dedecms.com', 1, 'sG93BJQ5wAB', 'Michigan');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Denise', 'Torres', 'dtorres33@cocolog-nifty.com', 1, 'Hmx4OG6sex', 'New Jersey');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Daniel', 'Dunn', 'ddunn34@va.gov', 1, 'ZM6heMM1F', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Tina', 'George', 'tgeorge35@guardian.co.uk', 1, 'lvlAZJVmOovM', 'Kentucky');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Thomas', 'Ross', 'tross36@toplist.cz', 1, '6JNJ9u', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Evelyn', 'Hughes', 'ehughes37@abc.net.au', 1, 'ntUr4AUhv', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Tammy', 'Alexander', 'talexander38@smh.com.au', 1, 'Nopy6t4EVOx', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Walter', 'Shaw', 'wshaw39@joomla.org', 1, 'aSQGHPlkZqR', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gary', 'Holmes', 'gholmes3a@uiuc.edu', 1, 'WLnWNQV', 'Utah');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gary', 'Frazier', 'gfrazier3b@lycos.com', 1, 'AiNe5v', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Benjamin', 'Gardner', 'bgardner3c@instagram.com', 1, 'ngAsiiOwW', 'Arkansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Alan', 'Cox', 'acox3d@amazon.de', 1, 'aSM7FNsE', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Frank', 'Phillips', 'fphillips3e@alibaba.com', 1, 'zfcwW8RGTEb', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Chris', 'Vasquez', 'cvasquez3f@tiny.cc', 1, 'TUAfSGgF5y', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Harold', 'Greene', 'hgreene3g@eepurl.com', 1, 'BZ9ab8', 'Connecticut');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Robin', 'Phillips', 'rphillips3h@ustream.tv', 1, '7Jo0RV', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Teresa', 'Larson', 'tlarson3i@topsy.com', 1, 'IyZbV8N', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Howard', 'Hamilton', 'hhamilton3j@bizjournals.com', 1, 'pTpInV', 'Michigan');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jean', 'Little', 'jlittle3k@slate.com', 1, '0FBaivlr', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Terry', 'Rodriguez', 'trodriguez3l@army.mil', 1, 'ZceDZxb', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Patrick', 'Washington', 'pwashington3m@webs.com', 1, 'gtldA4TWuX', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jonathan', 'Crawford', 'jcrawford3n@technorati.com', 1, '1We73hr3Ox', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Theresa', 'Mendoza', 'tmendoza3o@liveinternet.ru', 1, 'zFIpFz1mEK', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Matthew', 'West', 'mwest3p@php.net', 1, 'JUp1IibP', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Keith', 'Ferguson', 'kferguson3q@techcrunch.com', 1, '2vTH9qQekJT', 'North Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Edward', 'Armstrong', 'earmstrong3r@japanpost.jp', 1, 'OKaS3n9OW', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jeffrey', 'Lynch', 'jlynch3s@slashdot.org', 1, 'FAqTItljjB', 'Hawaii');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Henry', 'Price', 'hprice3t@booking.com', 1, 'spIowaE9HW', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Rose', 'Jacobs', 'rjacobs3u@dagondesign.com', 1, '8G3Q8FVb', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Janice', 'Hayes', 'jhayes3v@ted.com', 1, 'hbhXqt8Up', 'Kentucky');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Julie', 'White', 'jwhite3w@sina.com.cn', 1, 'oNuDCGBgxftm', 'Maryland');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Chris', 'Daniels', 'cdaniels3x@cnet.com', 1, 'UFIjHVBc6Y', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carolyn', 'Burton', 'cburton3y@gmpg.org', 1, 'CFIe7HlSnrzy', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ryan', 'Bishop', 'rbishop3z@buzzfeed.com', 1, '7m5qC4h', 'Tennessee');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Craig', 'Morales', 'cmorales40@nationalgeographic.com', 1, 'xupZUtOnU', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Heather', 'Bennett', 'hbennett41@joomla.org', 1, 'D9cEo8HVb', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sara', 'Fernandez', 'sfernandez42@irs.gov', 1, 'PknYrE46s', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Doris', 'Simpson', 'dsimpson43@amazon.de', 1, 'yWkfVxgdA4o', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jesse', 'Morris', 'jmorris44@diigo.com', 1, 'dTvRYVl1', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Charles', 'Morgan', 'cmorgan45@jimdo.com', 1, 'lX7sFDl2WP', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sean', 'Harper', 'sharper46@usa.gov', 1, 'UniG1xF1C', 'Kentucky');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Richard', 'Rice', 'rrice47@apache.org', 1, 'KZ7hhvltVP', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kathy', 'Andrews', 'kandrews48@businessinsider.com', 1, '83KCeLYoKgYu', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Donna', 'Hudson', 'dhudson49@java.com', 1, '5aORqsIMl', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carlos', 'Lawrence', 'clawrence4a@wufoo.com', 1, 'Q3FqDo', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Michael', 'Sims', 'msims4b@amazon.de', 1, 'pH3KYrsYUy4', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Laura', 'Green', 'lgreen4c@google.com.hk', 1, 'cAXPgPfDEAE', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Denise', 'Jenkins', 'djenkins4d@amazon.com', 1, 'jWPxqaLD09z', 'Colorado');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Donald', 'Hernandez', 'dhernandez4e@istockphoto.com', 1, '85w9jHI7', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sharon', 'Gutierrez', 'sgutierrez4f@fastcompany.com', 1, 'oriqW8', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Rebecca', 'Day', 'rday4g@indiatimes.com', 1, 'UE91TT', 'Colorado');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sandra', 'Crawford', 'scrawford4h@howstuffworks.com', 1, 'EUcTENzNf', 'Missouri');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Harold', 'Harvey', 'hharvey4i@dropbox.com', 1, 'N1lp9tAhjy', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Mary', 'Harris', 'mharris4j@ycombinator.com', 1, 'hM83ycOJ', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Randy', 'Price', 'rprice4k@uol.com.br', 1, 'FQnaXswmObh4', 'North Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jonathan', 'Johnston', 'jjohnston4l@blog.com', 1, '2634wxE', 'Illinois');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Harold', 'Mitchell', 'hmitchell4m@trellian.com', 1, 'eHq8LqFh14V', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Wanda', 'Fowler', 'wfowler4n@jigsy.com', 1, 'WvShoD3X', 'Missouri');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Matthew', 'Williams', 'mwilliams4o@homestead.com', 1, 'djeWxA', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Antonio', 'Ruiz', 'aruiz4p@instagram.com', 1, 'i3CWPCAOB', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Victor', 'Gonzalez', 'vgonzalez4q@quantcast.com', 1, 'VGXez23Lkn', 'Nevada');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christina', 'Perry', 'cperry4r@hp.com', 1, 'a8rp9i', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Robin', 'Thomas', 'rthomas4s@bigcartel.com', 1, 'AxtWn6eIVh', 'Maryland');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Helen', 'Butler', 'hbutler4t@jugem.jp', 1, 'EEWw6Gqx', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Richard', 'Robinson', 'rrobinson4u@vistaprint.com', 1, '5i6g19Nx', 'Kentucky');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Laura', 'Williams', 'lwilliams4v@auda.org.au', 1, 'FD6EFo', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('David', 'Wilson', 'dwilson4w@java.com', 1, 'mgd7XQ9i5UM', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jeffrey', 'Ross', 'jross4x@comcast.net', 1, 'p9Gzmfq', 'Hawaii');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Michael', 'Young', 'myoung4y@foxnews.com', 1, 'AVeHt4T1', 'South Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Justin', 'Banks', 'jbanks4z@senate.gov', 1, 'E5HBhbVs', 'South Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Clarence', 'Austin', 'caustin50@google.co.uk', 1, 'Aiwuef4IFnEH', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Mark', 'Brooks', 'mbrooks51@google.co.uk', 1, '5xKI8yu8', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gloria', 'Howell', 'ghowell52@xinhuanet.com', 1, 'Fmugp70l', 'Colorado');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Scott', 'Cruz', 'scruz53@chron.com', 1, 'shxN7GF', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Nicholas', 'Oliver', 'noliver54@topsy.com', 1, 'KDjJaBe9jKKU', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Brenda', 'Ferguson', 'bferguson55@army.mil', 1, 'HFuuApELqn', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Mark', 'Stanley', 'mstanley56@edublogs.org', 1, 'dcBJJ0', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Philip', 'Hernandez', 'phernandez57@w3.org', 1, 'Z7gUl4', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Anthony', 'Green', 'agreen58@ehow.com', 1, '6XYsUYspAf', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Henry', 'Sanchez', 'hsanchez59@quantcast.com', 1, 'csXluZAY', 'New Mexico');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Katherine', 'Long', 'klong5a@studiopress.com', 1, 'GlMNh65SpL', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Amanda', 'Bell', 'abell5b@csmonitor.com', 1, 'Eoxnqjf', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jane', 'Pierce', 'jpierce5c@utexas.edu', 1, 'AXk4r9T', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ashley', 'Thompson', 'athompson5d@weebly.com', 1, '7Q5FMYJp0', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jason', 'Fernandez', 'jfernandez5e@census.gov', 1, 'mqR9AclOdvhI', 'Arkansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Frank', 'Sanchez', 'fsanchez5f@psu.edu', 1, 'SACfZjP40GXs', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sara', 'Hill', 'shill5g@usa.gov', 1, 'Rt7lPOpMIo', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Willie', 'Long', 'wlong5h@weibo.com', 1, '9VIBNlD5YF', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carlos', 'Martinez', 'cmartinez5i@addtoany.com', 1, 'wAfQl9d2d', 'Oklahoma');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ernest', 'Weaver', 'eweaver5j@bigcartel.com', 1, 'RDN3bg', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Brandon', 'Simmons', 'bsimmons5k@europa.eu', 1, 'rL6i2y', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Irene', 'Hayes', 'ihayes5l@hp.com', 1, 'TIlE2MnNE', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('George', 'Jackson', 'gjackson5m@youtu.be', 1, 'dVDkhAV', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carl', 'Garcia', 'cgarcia5n@webeden.co.uk', 1, 'wTP14xD2qre', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Scott', 'Long', 'slong5o@4shared.com', 1, 'xjQCBwqNK', 'Connecticut');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Robert', 'Barnes', 'rbarnes5p@nba.com', 1, 'OgiG7lx', 'New Jersey');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joe', 'Romero', 'jromero5q@netscape.com', 1, 'nwdLmLCl', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ann', 'Jenkins', 'ajenkins5r@sakura.ne.jp', 1, 'w7ZZPG2', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Randy', 'Tucker', 'rtucker5s@ehow.com', 1, 'drIXmA4', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kenneth', 'Meyer', 'kmeyer5t@fastcompany.com', 1, 'qU9CLUmRO', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Elizabeth', 'Gibson', 'egibson5u@state.gov', 1, 'NN0HU3NzsUB', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jesse', 'Richards', 'jrichards5v@nih.gov', 1, 'I2PhbUnmUX4P', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Phillip', 'Montgomery', 'pmontgomery5w@hubpages.com', 1, 'Q7jIItlhW', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Roger', 'Nelson', 'rnelson5x@epa.gov', 1, 'JHKoMC', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Stephanie', 'Jacobs', 'sjacobs5y@aol.com', 1, '6pBEzF', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Howard', 'George', 'hgeorge5z@noaa.gov', 1, 'qx0pMsJDxKO5', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Howard', 'Griffin', 'hgriffin60@weebly.com', 1, 'OXiyY6W5wnLd', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Patrick', 'Scott', 'pscott61@utexas.edu', 1, 'VEBfem3BZSu', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Patricia', 'Burns', 'pburns62@nymag.com', 1, 'BgZoxbX', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Daniel', 'Ford', 'dford63@nih.gov', 1, 'kAX2w76BWvl', 'North Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Emily', 'Long', 'elong64@rediff.com', 1, 'i93plO', 'Colorado');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Betty', 'Taylor', 'btaylor65@hao123.com', 1, 'lE52Fa2bmi', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jeremy', 'Greene', 'jgreene66@nih.gov', 1, 'sUjeaf', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Timothy', 'Baker', 'tbaker67@reverbnation.com', 1, 'dZJpX8LP', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jean', 'West', 'jwest68@bloomberg.com', 1, 'nO0xW9nm', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jack', 'Reed', 'jreed69@cafepress.com', 1, 'uchBsK2', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ryan', 'Harrison', 'rharrison6a@i2i.jp', 1, 'nJ66vnU', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Scott', 'Jones', 'sjones6b@dion.ne.jp', 1, 'xP9EN8BRaHt', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jeremy', 'Howell', 'jhowell6c@cocolog-nifty.com', 1, 'hjm2SEufeqpf', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Eugene', 'Hunt', 'ehunt6d@timesonline.co.uk', 1, 'qdgpOT7J3uj1', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Nancy', 'Lawson', 'nlawson6e@mlb.com', 1, 'BXgDqPgRiL', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joyce', 'Flores', 'jflores6f@over-blog.com', 1, 'seFXRiUcw71m', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Thomas', 'Morgan', 'tmorgan6g@instagram.com', 1, 'aOsJEr6mwX', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Judy', 'Long', 'jlong6h@abc.net.au', 1, 'Xs4VfZ9eyz', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sharon', 'Webb', 'swebb6i@bravesites.com', 1, 'D30W4lEKIQM', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gregory', 'Sanchez', 'gsanchez6j@loc.gov', 1, 'WOIDjISLPU', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Anne', 'Webb', 'awebb6k@pinterest.com', 1, 'ppthf23rQ', 'Michigan');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Deborah', 'Hayes', 'dhayes6l@cdbaby.com', 1, 'Hih3L4zNZ71', 'Iowa');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Walter', 'Warren', 'wwarren6m@bbc.co.uk', 1, 'Bby2ZPQgJdl', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gerald', 'George', 'ggeorge6n@unblog.fr', 1, 'KS2jiuOUW', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gerald', 'Williamson', 'gwilliamson6o@guardian.co.uk', 1, 'W1T0lOgxa7', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Shirley', 'Stewart', 'sstewart6p@symantec.com', 1, 'Zk349CXV', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christina', 'Shaw', 'cshaw6q@hud.gov', 1, '1bT8xX5y5', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joyce', 'Reed', 'jreed6r@accuweather.com', 1, 'o7JRuo', 'Maryland');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Willie', 'Elliott', 'welliott6s@time.com', 1, 'sWxzx2', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Scott', 'Price', 'sprice6t@mozilla.org', 1, 'JMbS4d0opgng', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joshua', 'Kim', 'jkim6u@sogou.com', 1, 'FFux5rK', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Annie', 'Walker', 'awalker6v@cyberchimps.com', 1, 'Od0LLb', 'Illinois');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Judy', 'Peters', 'jpeters6w@webeden.co.uk', 1, 'K81Pea0ysr5', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Andrew', 'Owens', 'aowens6x@google.co.jp', 1, 'NA9Cvb', 'Oregon');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Laura', 'Gutierrez', 'lgutierrez6y@xing.com', 1, 'SUrSml', 'Oklahoma');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ruth', 'Holmes', 'rholmes6z@edublogs.org', 1, '7HV2cJN', 'Michigan');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Denise', 'Dixon', 'ddixon70@irs.gov', 1, 'h14rJ91bH', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sandra', 'Little', 'slittle71@pbs.org', 1, '3WsXYoKtK9Q8', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Anne', 'Banks', 'abanks72@t.co', 1, 'sqFCkp', 'Michigan');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christine', 'Morgan', 'cmorgan73@rediff.com', 1, 'aaUBpXiJ', 'Kansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christopher', 'Andrews', 'candrews74@google.ru', 1, 'bafqIhCE', 'New Hampshire');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gregory', 'Hicks', 'ghicks75@boston.com', 1, 'EWT1vL', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Howard', 'Lynch', 'hlynch76@bloglovin.com', 1, 'an2Awz', 'Oklahoma');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Frances', 'Kelly', 'fkelly77@netscape.com', 1, 'JrQGVnclncU', 'Illinois');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Walter', 'Austin', 'waustin78@merriam-webster.com', 1, 'nqPHFiBB1m', 'Missouri');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Paula', 'Tucker', 'ptucker79@hud.gov', 1, 'eHRLvbZYo', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Susan', 'Carpenter', 'scarpenter7a@instagram.com', 1, 'uKDUko0IUwm', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Judith', 'Rice', 'jrice7b@cafepress.com', 1, '1YSRNIh3', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Michael', 'Hansen', 'mhansen7c@thetimes.co.uk', 1, 'zIVZ84QVhVye', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Teresa', 'Moore', 'tmoore7d@walmart.com', 1, 'Nzh8XXRBU6', 'Mississippi');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christopher', 'Stanley', 'cstanley7e@aol.com', 1, '8cQ2AWe', 'Kentucky');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Paula', 'Coleman', 'pcoleman7f@oakley.com', 1, 'Qr0FxftAL', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Terry', 'Franklin', 'tfranklin7g@godaddy.com', 1, 'XgRmYnhb0l', 'Iowa');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Antonio', 'Hansen', 'ahansen7h@ted.com', 1, 'RFYpVW', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Lori', 'Webb', 'lwebb7i@admin.ch', 1, 'gzT9YgkZJ', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carol', 'Patterson', 'cpatterson7j@slideshare.net', 1, 'QH36F3', 'Michigan');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Chris', 'Perkins', 'cperkins7k@ucoz.com', 1, '4uLqiwHZW', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carl', 'Gonzales', 'cgonzales7l@quantcast.com', 1, 'cPt9at', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jesse', 'Medina', 'jmedina7m@chron.com', 1, 'Mxk3DDihr', 'Delaware');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diane', 'Hansen', 'dhansen7n@msu.edu', 1, 'N5ejUF2aSU', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Patricia', 'Brown', 'pbrown7o@etsy.com', 1, 'WaryCg4', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Patricia', 'Ward', 'pward7p@cafepress.com', 1, 'fXjy0pDll', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Andrea', 'Boyd', 'aboyd7q@globo.com', 1, '2qZUxx', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Debra', 'Thompson', 'dthompson7r@bandcamp.com', 1, '1KFd93qMn', 'Kansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jennifer', 'Franklin', 'jfranklin7s@techcrunch.com', 1, 'ahNOuKy', 'Tennessee');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Amanda', 'George', 'ageorge7t@bluehost.com', 1, 'gDBsBHE5PX', 'Delaware');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Craig', 'Peterson', 'cpeterson7u@elpais.com', 1, 'QLrVF7AICab5', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Frank', 'Perry', 'fperry7v@opensource.org', 1, 'cnxJ02eLS6MJ', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Angela', 'Warren', 'awarren7w@umich.edu', 1, 'sgC5fBgt', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Heather', 'Murphy', 'hmurphy7x@ted.com', 1, 'V5D2R3', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joshua', 'Bell', 'jbell7y@wp.com', 1, 'LfnWIF', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Chris', 'Day', 'cday7z@flickr.com', 1, 'xScYw2Mj', 'Wisconsin');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Frances', 'Weaver', 'fweaver80@ebay.co.uk', 1, 'fCoieyrINX5', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Robert', 'Jenkins', 'rjenkins81@bluehost.com', 1, '84fVRy3mUHo', 'Maryland');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Helen', 'Mccoy', 'hmccoy82@xinhuanet.com', 1, 'gzBdZKNFk', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Todd', 'Ryan', 'tryan83@utexas.edu', 1, 'Z3ME4QW5Bh', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jean', 'Clark', 'jclark84@stumbleupon.com', 1, 'UJ6kaYq8', 'Missouri');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Bonnie', 'Rodriguez', 'brodriguez85@ucsd.edu', 1, 'D04LVvN', 'Connecticut');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kelly', 'Miller', 'kmiller86@google.com.br', 1, 'M2ZHDc9', 'Nebraska');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jack', 'Rodriguez', 'jrodriguez87@1688.com', 1, 'cRTm7SaBHI2', 'Illinois');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Stephanie', 'Allen', 'sallen88@google.co.uk', 1, 'LagXF9xExR', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Fred', 'Dunn', 'fdunn89@facebook.com', 1, 'mm0x1AyFTvEH', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ronald', 'Foster', 'rfoster8a@nsw.gov.au', 1, '6YcVImlRAI', 'New Jersey');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Martin', 'Crawford', 'mcrawford8b@wikispaces.com', 1, '76ERJV', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Debra', 'Rose', 'drose8c@dedecms.com', 1, 'FqtthslPAFV', 'Missouri');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kimberly', 'Burton', 'kburton8d@ft.com', 1, 'Uy9LToMf5CC', 'Wisconsin');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Wayne', 'Jacobs', 'wjacobs8e@cloudflare.com', 1, 'E3eGnfjgV', 'Tennessee');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sarah', 'Burns', 'sburns8f@tmall.com', 1, 'ElVXlzM', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Anne', 'Hall', 'ahall8g@google.it', 1, 'kcTVpm8NJ4', 'Wisconsin');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Laura', 'Nguyen', 'lnguyen8h@gov.uk', 1, 'f7Wh6DYvGijZ', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Amanda', 'Chavez', 'achavez8i@goo.ne.jp', 1, 'G52WGJT4o6C', 'West Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Donald', 'Richardson', 'drichardson8j@goodreads.com', 1, 'QnymSMN', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diane', 'Parker', 'dparker8k@fda.gov', 1, 'ZAKwrUKkF1', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('John', 'Morales', 'jmorales8l@mashable.com', 1, 'IBqlfHM', 'Iowa');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Mildred', 'Brown', 'mbrown8m@trellian.com', 1, 'RtLWOErbx0rt', 'Illinois');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jesse', 'Snyder', 'jsnyder8n@dmoz.org', 1, 'rQlIsFN', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Brandon', 'Hicks', 'bhicks8o@nifty.com', 1, 'avcyoWiWz', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joyce', 'Reed', 'jreed8p@123-reg.co.uk', 1, 'sKFSvMorPiu7', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Marie', 'Gomez', 'mgomez8q@twitter.com', 1, 'Mr4nQdOq7', 'Michigan');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joshua', 'Hughes', 'jhughes8r@soup.io', 1, 'P1YXF2cFQw', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jose', 'Gray', 'jgray8s@php.net', 1, 'QmRiIJ3y', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Melissa', 'Lopez', 'mlopez8t@opera.com', 1, 'CGW6G1eugi', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Victor', 'James', 'vjames8u@fastcompany.com', 1, 'gFPYde9k9PJw', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Juan', 'Cole', 'jcole8v@blog.com', 1, 'si0REVKFuo', 'Wisconsin');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jacqueline', 'Martinez', 'jmartinez8w@cnn.com', 1, 'wC4Nl2', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Amy', 'Boyd', 'aboyd8x@theguardian.com', 1, 'ulwmO9Q2', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kevin', 'Oliver', 'koliver8y@wunderground.com', 1, 'vRHFb6Ng', 'Illinois');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Barbara', 'Sullivan', 'bsullivan8z@weebly.com', 1, '0zYJ2zFFe', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Melissa', 'Hernandez', 'mhernandez90@imdb.com', 1, '3ASqdWdji', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Fred', 'Ortiz', 'fortiz91@posterous.com', 1, 'trMuszh', 'West Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Raymond', 'Wilson', 'rwilson92@house.gov', 1, 'RY0ifs3DJ', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gerald', 'Pierce', 'gpierce93@reverbnation.com', 1, 'jE9DSi', 'Maryland');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Denise', 'Richards', 'drichards94@paypal.com', 1, '9T6ejn', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ralph', 'Jacobs', 'rjacobs95@edublogs.org', 1, 'bC5MDV5Tgw', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jose', 'Lawrence', 'jlawrence96@blinklist.com', 1, 'JGDwuF', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ronald', 'Boyd', 'rboyd97@nydailynews.com', 1, 'JXZ3bsb', 'Colorado');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Timothy', 'Myers', 'tmyers98@economist.com', 1, '6VHmTjzMd', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jimmy', 'Freeman', 'jfreeman99@sourceforge.net', 1, 'b650jrs', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Martha', 'Richards', 'mrichards9a@nature.com', 1, 'urRsrk0Q', 'New Jersey');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Dennis', 'Alvarez', 'dalvarez9b@utexas.edu', 1, 'CBZ2HQ', 'Iowa');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Johnny', 'Harrison', 'jharrison9c@w3.org', 1, 'AiitvGLcR3F', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Debra', 'Peters', 'dpeters9d@senate.gov', 1, 'pbO6hGXE', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Marilyn', 'Patterson', 'mpatterson9e@bigcartel.com', 1, 'Cg38yv6x', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Barbara', 'Bailey', 'bbailey9f@example.com', 1, 'Ito1j0', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Teresa', 'Morris', 'tmorris9g@amazon.co.uk', 1, 'qijRRdMkFo8d', 'Massachusetts');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Willie', 'Cruz', 'wcruz9h@nasa.gov', 1, '6yYaAtOd5D', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('William', 'Willis', 'wwillis9i@unblog.fr', 1, 'fjNo2bSy', 'Nebraska');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diane', 'Murphy', 'dmurphy9j@addtoany.com', 1, '8M7ICy1MQ4', 'Colorado');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ernest', 'Mills', 'emills9k@histats.com', 1, 'iNfTAR', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Laura', 'Wagner', 'lwagner9l@is.gd', 1, 'D77ChUG6', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Adam', 'Graham', 'agraham9m@xing.com', 1, 'KMjuM0i2G', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('James', 'Lopez', 'jlopez9n@360.cn', 1, 'nuF8wTFc', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Rebecca', 'Garcia', 'rgarcia9o@yale.edu', 1, '3OlXyyf', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Scott', 'Thompson', 'sthompson9p@issuu.com', 1, 'hYX5wqrHYns', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kimberly', 'Ross', 'kross9q@illinois.edu', 1, '1ltwdef', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sara', 'Murphy', 'smurphy9r@sfgate.com', 1, '2uUlcsTraYT', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Bruce', 'Bryant', 'bbryant9s@clickbank.net', 1, 'IofkkHldN', 'Illinois');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Mildred', 'Hansen', 'mhansen9t@dell.com', 1, 'tw5eBkg1', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Karen', 'Mendoza', 'kmendoza9u@skyrock.com', 1, 'rZ7ZwHx', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ryan', 'Chapman', 'rchapman9v@devhub.com', 1, 'Bok9wLxq2tL', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Randy', 'Henderson', 'rhenderson9w@parallels.com', 1, '0DMyJE9e', 'Maryland');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Randy', 'Porter', 'rporter9x@arstechnica.com', 1, 'OjStXQ8', 'Utah');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('James', 'Grant', 'jgrant9y@sciencedirect.com', 1, 'jJM5wZ', 'Oklahoma');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carolyn', 'Marshall', 'cmarshall9z@spotify.com', 1, 'ODFGQdVeR', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joan', 'Long', 'jlonga0@addtoany.com', 1, 'FzKDk1YsB4t', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christina', 'Long', 'clonga1@blogtalkradio.com', 1, '7E62fu', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Robin', 'Ramos', 'rramosa2@disqus.com', 1, 'bBW0fxzCt', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jennifer', 'Kelly', 'jkellya3@unblog.fr', 1, 'OnUgehGxzZ', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Debra', 'Knight', 'dknighta4@fastcompany.com', 1, '55qTV2XKlQ9', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Keith', 'Scott', 'kscotta5@g.co', 1, 'sRdBdfX4q', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Norma', 'Lynch', 'nlyncha6@nifty.com', 1, 'Z2NLGLBCk', 'North Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Helen', 'Cox', 'hcoxa7@archive.org', 1, 'rGFATq', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Shirley', 'Thomas', 'sthomasa8@squidoo.com', 1, '4bI0KbZbum', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kathryn', 'Richardson', 'krichardsona9@discuz.net', 1, '4YHvUNSS', 'Illinois');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christina', 'Elliott', 'celliottaa@eventbrite.com', 1, 'NIvynBqLR', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sandra', 'Lee', 'sleeab@unc.edu', 1, 'pb2m5cv', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jennifer', 'Harvey', 'jharveyac@bigcartel.com', 1, '6z26V7A', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Wayne', 'Ramirez', 'wramirezad@state.tx.us', 1, 'w32JAeMxDg1K', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diana', 'Gray', 'dgrayae@angelfire.com', 1, '9y4JxYAkO', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carol', 'Romero', 'cromeroaf@shutterfly.com', 1, '7OmR9NFcMoBB', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Anna', 'Fisher', 'afisherag@w3.org', 1, 'lv1EDDn9hRo', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Frank', 'Thomas', 'fthomasah@newyorker.com', 1, '7hBuvVUMOjP', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Margaret', 'Palmer', 'mpalmerai@jugem.jp', 1, 'W3L4va', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Patrick', 'Garcia', 'pgarciaaj@sbwire.com', 1, 'Ahy0uLzk', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ernest', 'Peterson', 'epetersonak@time.com', 1, 'E7UyTFWr', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Paula', 'Welch', 'pwelchal@usa.gov', 1, '4YJXNrr', 'Tennessee');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Margaret', 'Alexander', 'malexanderam@wikimedia.org', 1, 'hub59x', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Rose', 'Perry', 'rperryan@soundcloud.com', 1, '73mr2IlHkEu', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christina', 'Pierce', 'cpierceao@psu.edu', 1, 'V59z3YUZ', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Rebecca', 'Riley', 'rrileyap@cargocollective.com', 1, 'FjsEdfWeEgz', 'Maryland');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christina', 'Evans', 'cevansaq@usnews.com', 1, '320YNKxlXqTK', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Fred', 'Morales', 'fmoralesar@bravesites.com', 1, 'JVfHYkai', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christina', 'Lynch', 'clynchas@squidoo.com', 1, 'aXN96zrTgH', 'Nebraska');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Emily', 'Lawson', 'elawsonat@skype.com', 1, 'M2TEC5YFN8IU', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Stephen', 'Owens', 'sowensau@topsy.com', 1, 'xsRSlnlZKTdr', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jessica', 'Matthews', 'jmatthewsav@mapy.cz', 1, 'YMFLBARF0', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joseph', 'Lawrence', 'jlawrenceaw@mediafire.com', 1, 'kAh5M0G', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Margaret', 'Austin', 'maustinax@bandcamp.com', 1, 'I0Ibywli', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Evelyn', 'Davis', 'edavisay@so-net.ne.jp', 1, 'hyGpFOhus', 'Wisconsin');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kathleen', 'Collins', 'kcollinsaz@php.net', 1, 'ahhukFIGI26', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Denise', 'Hudson', 'dhudsonb0@wufoo.com', 1, 'iIQ6rm8b1Gc', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Wayne', 'Boyd', 'wboydb1@home.pl', 1, 'A0HPAHoHCUc', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Helen', 'Burns', 'hburnsb2@uol.com.br', 1, 'OYNVgfL', 'Tennessee');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Tammy', 'Stanley', 'tstanleyb3@dailymotion.com', 1, 'pCU252go', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jeffrey', 'Knight', 'jknightb4@feedburner.com', 1, 'tTGxxU7ZuXj', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Bonnie', 'Hanson', 'bhansonb5@cbc.ca', 1, 'DTWAEMeixX3j', 'Oklahoma');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Patrick', 'James', 'pjamesb6@etsy.com', 1, 'w0rs41', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Richard', 'Hart', 'rhartb7@tripod.com', 1, 'UD0rW7HLlzw', 'Utah');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kathleen', 'Knight', 'kknightb8@people.com.cn', 1, 'pWqei0q2', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jennifer', 'Arnold', 'jarnoldb9@cloudflare.com', 1, '87668ay3frn', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Louis', 'Lewis', 'llewisba@live.com', 1, 'Pxvf5Mt4c', 'Kentucky');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Keith', 'Owens', 'kowensbb@yolasite.com', 1, 'iedyiaHvL0', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Donna', 'Spencer', 'dspencerbc@independent.co.uk', 1, 'a06xPdJl', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Roger', 'Wheeler', 'rwheelerbd@ted.com', 1, '9V7UVD', 'South Dakota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Robert', 'Foster', 'rfosterbe@globo.com', 1, 'sUzP4QpHN', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Alice', 'Stevens', 'astevensbf@ibm.com', 1, '8jQvS9g', 'Missouri');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Beverly', 'Hunter', 'bhunterbg@so-net.ne.jp', 1, 'vACbrx', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Phillip', 'Gutierrez', 'pgutierrezbh@alexa.com', 1, 'a1V1c9', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kathryn', 'Foster', 'kfosterbi@i2i.jp', 1, 'yUPn60p', 'Oklahoma');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Irene', 'Evans', 'ievansbj@dedecms.com', 1, 'A8IPirrx', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Louise', 'Nelson', 'lnelsonbk@youtu.be', 1, 'pkRzeJ', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Richard', 'Martin', 'rmartinbl@europa.eu', 1, 'Kzmvy6S', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Emily', 'Ferguson', 'efergusonbm@prlog.org', 1, 'QovAcnD', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Antonio', 'Rose', 'arosebn@scientificamerican.com', 1, 'gAWviU4U', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Bruce', 'Bishop', 'bbishopbo@nba.com', 1, 'tpoEG1mE', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Samuel', 'Ward', 'swardbp@wikispaces.com', 1, 'WfwsEqyaAnp', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Raymond', 'West', 'rwestbq@dagondesign.com', 1, 'sgwCFee2Qb8', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jeremy', 'Ross', 'jrossbr@php.net', 1, 'mvEQQwsBzY', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Wayne', 'Hart', 'whartbs@g.co', 1, 'Gpr1F4Z', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sharon', 'Dunn', 'sdunnbt@examiner.com', 1, 'YXkioqyEQ', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Janice', 'Cole', 'jcolebu@marketwatch.com', 1, 'lqXHhIM0G', 'Illinois');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Brian', 'Willis', 'bwillisbv@hostgator.com', 1, '4VK8HcqXzD', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Wayne', 'Wright', 'wwrightbw@constantcontact.com', 1, '7haJu5dc55', 'Massachusetts');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Matthew', 'Price', 'mpricebx@ning.com', 1, 'cvY67bIr9qd', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Alan', 'Carroll', 'acarrollby@psu.edu', 1, 'BQwMtMI5uX', 'Maryland');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Paula', 'Frazier', 'pfrazierbz@stanford.edu', 1, 'c7EaHe2', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Eugene', 'Rice', 'ericec0@drupal.org', 1, 'qPI8PDy4', 'Mississippi');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Beverly', 'Lawson', 'blawsonc1@imageshack.us', 1, 'HTQF41BbN', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Nicole', 'Ryan', 'nryanc2@salon.com', 1, 'TWcHZoY', 'Kentucky');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Teresa', 'Mills', 'tmillsc3@intel.com', 1, 'UX7BfdOAMx', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jane', 'Martin', 'jmartinc4@home.pl', 1, 'jG09Qv', 'Missouri');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Paul', 'White', 'pwhitec5@state.tx.us', 1, 'jdiNtUu', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Fred', 'Williams', 'fwilliamsc6@cloudflare.com', 1, 'P83OXq', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Wayne', 'Shaw', 'wshawc7@arizona.edu', 1, 'utSPKH7Rg', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sean', 'Hudson', 'shudsonc8@ucla.edu', 1, 'cBy9ottPadX2', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Arthur', 'Ferguson', 'afergusonc9@soundcloud.com', 1, 'MUtvdS0wtSC', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Brandon', 'Berry', 'bberryca@walmart.com', 1, 'bimgjQ9A6V', 'Oklahoma');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Dennis', 'Carr', 'dcarrcb@xrea.com', 1, 'zLvSTKiAYXd', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Alice', 'Harvey', 'aharveycc@macromedia.com', 1, 'nM8WYsEDWb', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Melissa', 'Cole', 'mcolecd@g.co', 1, 'TeNgXYnRWDnu', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Sandra', 'Weaver', 'sweaverce@creativecommons.org', 1, 'SefiggoLW', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Thomas', 'Duncan', 'tduncancf@cnet.com', 1, 'dQydkRIpGp', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carol', 'Powell', 'cpowellcg@hatena.ne.jp', 1, 'cCGXL5', 'Kansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jack', 'Holmes', 'jholmesch@sogou.com', 1, 'qO0XUNQkz', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Rachel', 'Roberts', 'rrobertsci@nymag.com', 1, 'ZqKSa6C', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Bobby', 'Sanders', 'bsanderscj@gravatar.com', 1, 'JW1saLdYmntd', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Lawrence', 'Campbell', 'lcampbellck@geocities.jp', 1, 'LFciYhVqj', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('James', 'Evans', 'jevanscl@whitehouse.gov', 1, 'YvpTjB6', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diane', 'George', 'dgeorgecm@wsj.com', 1, 'RwoeLtr3Am', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kenneth', 'Adams', 'kadamscn@businessweek.com', 1, 'R8Nhhwx8D', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Maria', 'Rivera', 'mriveraco@telegraph.co.uk', 1, 'mvOibaXVxdFA', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Howard', 'Perez', 'hperezcp@aboutads.info', 1, 'pLaXKur3Z', 'Iowa');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ronald', 'Ryan', 'rryancq@phoca.cz', 1, 'uYQyyU9n8', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Lori', 'Rose', 'lrosecr@prlog.org', 1, 'ykKe0mwV', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jesse', 'Moreno', 'jmorenocs@nyu.edu', 1, 'gCA2cx', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Evelyn', 'Stevens', 'estevensct@newyorker.com', 1, 'Ij2Vscn', 'North Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Gloria', 'Woods', 'gwoodscu@istockphoto.com', 1, 'oZmWO521CG3', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Phyllis', 'Pierce', 'ppiercecv@blogs.com', 1, '945FEpX', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Betty', 'Parker', 'bparkercw@un.org', 1, '84O1GWz2n', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Phillip', 'Brown', 'pbrowncx@bloglovin.com', 1, '7VwKhYQd', 'Montana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Christine', 'Arnold', 'carnoldcy@scientificamerican.com', 1, 'Y28KGxEsgY', 'Massachusetts');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Juan', 'Watkins', 'jwatkinscz@cafepress.com', 1, 'Z8bJym', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Teresa', 'Cook', 'tcookd0@ftc.gov', 1, 'AdJWEgF9', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Ruby', 'Riley', 'rrileyd1@sohu.com', 1, 'KuBDcKhhEZkc', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jose', 'Gonzalez', 'jgonzalezd2@lulu.com', 1, '18CUOnd', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Billy', 'Perkins', 'bperkinsd3@go.com', 1, 'NauNodYa', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Barbara', 'Richards', 'brichardsd4@elegantthemes.com', 1, 'idZizZK', 'New Jersey');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jerry', 'Lane', 'jlaned5@reddit.com', 1, 'czXmsMgjrZ', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Julie', 'Green', 'jgreend6@typepad.com', 1, 'Rdj8Mchg', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Mildred', 'Barnes', 'mbarnesd7@usatoday.com', 1, 'Z2byHvn7iuA', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kevin', 'Harris', 'kharrisd8@ebay.co.uk', 1, 'NY9w7dm5TI2d', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jeremy', 'Rogers', 'jrogersd9@wordpress.org', 1, 'rTXwgJRi22Y', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Bobby', 'Wright', 'bwrightda@baidu.com', 1, '3e0CgSEOb8b1', 'West Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jesse', 'Williamson', 'jwilliamsondb@sakura.ne.jp', 1, 'jcPMlJDlsHpL', 'Ohio');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Lisa', 'Lynch', 'llynchdc@ucoz.ru', 1, 'o7klJVdyuTY', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Lillian', 'Richards', 'lrichardsdd@vimeo.com', 1, 'uWWUUfj', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Betty', 'Black', 'bblackde@si.edu', 1, 'CgIBQW', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Wanda', 'Green', 'wgreendf@diigo.com', 1, 'miigDgC7jj', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Aaron', 'Welch', 'awelchdg@craigslist.org', 1, 'KLDplaX4xsDq', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jesse', 'Howard', 'jhowarddh@arstechnica.com', 1, 'ZCBND4B16x', 'Oklahoma');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Brian', 'Parker', 'bparkerdi@ihg.com', 1, 'PFN7tOfM40Cn', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jonathan', 'White', 'jwhitedj@seattletimes.com', 1, '0FfHEEQCQnB', 'Kansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jack', 'Freeman', 'jfreemandk@usatoday.com', 1, 'iUeVYKz', 'Connecticut');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Wanda', 'Howell', 'whowelldl@hp.com', 1, 'diyumdl', 'Colorado');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Janice', 'Anderson', 'jandersondm@home.pl', 1, '8zD44O', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Walter', 'Sullivan', 'wsullivandn@wiley.com', 1, 'O3AewW0oO1', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Amy', 'Chavez', 'achavezdo@toplist.cz', 1, 'MNMfQd9ugozn', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jeremy', 'Weaver', 'jweaverdp@tripod.com', 1, 'GVGaUf', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joe', 'Long', 'jlongdq@un.org', 1, 'PfkfbwGZd6FC', 'Kentucky');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('David', 'Ramirez', 'dramirezdr@admin.ch', 1, 'KEHBGClU4jRa', 'North Dakota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Mark', 'Hayes', 'mhayesds@guardian.co.uk', 1, 'nmMU1TMdzrht', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diane', 'Alvarez', 'dalvarezdt@prweb.com', 1, 'ljMvh2gIguBA', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Paul', 'Fisher', 'pfisherdu@lulu.com', 1, '4gUqJEfX4Y', 'Indiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kevin', 'Elliott', 'kelliottdv@pbs.org', 1, 'PnTPgYnw', 'New Mexico');
