insert into award_user (first_name, last_name, email, act_id, password, state) values ('Kyle', 'Bedell', 'kyle.bedell@gmail.com', 2, '1', 'Michigan');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carl', 'Jones', 'cjones0@cargocollective.com', 2, '1r5KMp4AQh', 'Massachusetts');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Steven', 'Reid', 'sreid1@nifty.com', 2, 'JRF1amVR1y', 'Nebraska');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Antonio', 'Phillips', 'aphillips2@behance.net', 2, 'Q6wm7hBf', 'Washington');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Alan', 'Wallace', 'awallace3@msu.edu', 2, 'N7Vm7Gmo', 'Massachusetts');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Benjamin', 'Porter', 'bporter4@bloomberg.com', 2, '6bkpRywEHdR', 'Louisiana');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Keith', 'Harvey', 'kharvey5@alibaba.com', 2, 'oWG5o2ueVBEM', 'Wisconsin');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Timothy', 'Ellis', 'tellis6@newyorker.com', 2, 'O4mpKdgdIe8', 'North Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Edward', 'Gray', 'egray7@unc.edu', 2, '7ejgQDNiuWsz', 'Oregon');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Alice', 'Vasquez', 'avasquez8@oracle.com', 2, 'K2vIf3dTFl', 'South Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Willie', 'Mason', 'wmason9@cyberchimps.com', 2, 'cq0hkRiXjErK', 'Maryland');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Teresa', 'Daniels', 'tdanielsa@wufoo.com', 2, '8uqG5fPIMg', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Heather', 'Carroll', 'hcarrollb@scientificamerican.com', 2, '27mtO49B8w', 'Kentucky');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Phyllis', 'Hanson', 'phansonc@technorati.com', 2, 'RSiJY30IK3gr', 'Nebraska');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Catherine', 'Nguyen', 'cnguyend@admin.ch', 2, 'O3S98k3nr', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('William', 'Rice', 'wricee@squarespace.com', 2, 'TzS4v9', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Benjamin', 'Jordan', 'bjordanf@bloglines.com', 2, 'LMeAf44zbdX', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jane', 'Walker', 'jwalkerg@theguardian.com', 2, 'R1oaJUr', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Irene', 'Reid', 'ireidh@lycos.com', 2, 'AD8D0u2Vvtl', 'Kansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Barbara', 'Jacobs', 'bjacobsi@hatena.ne.jp', 2, 'vXSSZWF', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carlos', 'Mccoy', 'cmccoyj@virginia.edu', 2, 'UFo48d5', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Daniel', 'Gomez', 'dgomezk@nytimes.com', 2, 'nvuTlUYV', 'Arizona');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Susan', 'Bradley', 'sbradleyl@bigcartel.com', 2, 'RrsK4kqK', 'Kansas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Marilyn', 'Simmons', 'msimmonsm@google.es', 2, 'n0r78FbXPE', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Thomas', 'Castillo', 'tcastillon@whitehouse.gov', 2, '6xVb68d', 'New York');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Amy', 'Martinez', 'amartinezo@storify.com', 2, '5QxDSe', 'South Dakota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Todd', 'Howard', 'thowardp@histats.com', 2, 'etdzoyZln', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Lori', 'Gonzales', 'lgonzalesq@netvibes.com', 2, '444XkU', 'Massachusetts');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diana', 'Hunter', 'dhunterr@si.edu', 2, '54gavUZjH', 'Alabama');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Doris', 'Montgomery', 'dmontgomerys@tmall.com', 2, '4Hjro9nchS8', 'Georgia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Donald', 'Washington', 'dwashingtont@jimdo.com', 2, 'TBD83ewZTZS', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Lois', 'Myers', 'lmyersu@fc2.com', 2, 'lNEWCIMYEPcT', 'North Carolina');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Joan', 'Ramirez', 'jramirezv@ucsd.edu', 2, 'EF8BPOq', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Linda', 'Austin', 'laustinw@archive.org', 2, 'k1dTLaNBaG', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jean', 'Matthews', 'jmatthewsx@symantec.com', 2, 'L9LIwTthMp', 'Tennessee');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Jason', 'Stephens', 'jstephensy@mac.com', 2, 'yiD4390U3', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Earl', 'Harris', 'eharrisz@sourceforge.net', 2, 'u7K4WDrYE1ol', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Aaron', 'Collins', 'acollins10@storify.com', 2, 'L0itMGmnCuyn', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Carolyn', 'Hayes', 'chayes11@issuu.com', 2, 'HyZ3KuRTPvg', 'Utah');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Clarence', 'Rogers', 'crogers12@sciencedirect.com', 2, 'Bjco7D', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Mark', 'Coleman', 'mcoleman13@apple.com', 2, 'g3WoYwfDTHF', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Diane', 'Garrett', 'dgarrett14@dell.com', 2, 'tvybwZT', 'Virginia');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('James', 'Rice', 'jrice15@unc.edu', 2, 'fOExoM5', 'Mississippi');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Frank', 'Sims', 'fsims16@github.io', 2, '2jPSoN0', 'Alaska');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Martha', 'Carr', 'mcarr17@taobao.com', 2, '2vK4XB7BOb1U', 'Florida');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Chris', 'Clark', 'cclark18@jigsy.com', 2, 'DrDDepg1', 'Idaho');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Henry', 'Green', 'hgreen19@uol.com.br', 2, 'YhASlBKz7', 'Texas');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Adam', 'Robertson', 'arobertson1a@cbslocal.com', 2, 'nhZlyg4wjR', 'Minnesota');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Eric', 'Lynch', 'elynch1b@fema.gov', 2, 'hoS4jZ', 'Pennsylvania');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Eugene', 'Simmons', 'esimmons1c@csmonitor.com', 2, 'lETDu2NCT', 'California');
insert into award_user (first_name, last_name, email, act_id, password, state) values ('Juan', 'Moreno', 'jmoreno1d@parallels.com', 2, '11g4zLi9tYTZ', 'Massachusetts');
